### Get request
GET http://localhost:8080/books

### Get request with a query parameter
GET http://localhost:8080/books/search?term=tOLKIEN

### Post request
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Internazionale Road to Munchen",
  "author": "Stam",
  "pages": 982,
  "year": 2025,
  "genres": [
    "Drama"
  ],
  "synopsis": "Leiyn Firebrand is no stranger to a fight. A brash ranger of the Titan Wilds..",
  "cover": "https://m.media-amazon.com/images/I/91qynloe1gL._SY522_.jpg",
  "publishedAt": "2020-04-10T00:00:00Z",
  "reviews": [
    {
      "date": "2025-04-10T00:00:00Z",
      "user": {
          "id": "001",
          "name": "Marcos"
      },
      "message": "I love this book!",
      "stars": 5
    }
  ]
}

### Post request to group books
POST http://localhost:8080/books/groupByAuthorAndExport

### Post request to export books with published year
POST http://localhost:8080/books/exportBooksWithPublishedYear


