### Get request
GET http://localhost:8080/books

### Get request with a query parameter
GET http://localhost:8080/books/search?term=scenes

### Post request
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Tricked (Fairy Tale Reform School Book 3)",
  "author": "Jen Calonita",
  "pages": 258,
  "year": 2023,
  "genres": [
    "Drama"
  ],
  "synopsis": "Things are changing at Fairy Tale Reform School. At least, that's what Gilly's heard through the Enchantasia rumor mill.",
  "cover": "https://images.isbndb.com/covers/40/60/9780002554060.jpg"
}

### Post request to group books
POST http://localhost:8080/books/groupByAuthorAndExport


